###
GET http://localhost:5000/api/tenant/
###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
   "tenantName": "New Buotique",
    "logo": "null",
    "admin": {
      "name": "Wudiri",
      "email": "wudiri1@gmail.com",
      "password": "wudiri",
      "role": "SUPER_ADMIN"
    }
 }

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "wudiri1@gmail.com",
  "password": "wudiri"
}

### Get Current User
GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiOWNkZTQ5LTdjYmMtNDFmOS04NGU3LTY5YWI2ZjdjMDBjNSIsImVtYWlsIjoid3VkaXJpMUBnbWFpbC5jb20iLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJ0ZW5hbnRJZCI6ImNlMGEyOWM3LWUzZDUtNGViMi1iYzIzLTg3NGFjNmM2YjMxNSIsImlhdCI6MTc2OTU0Mzg1NiwiZXhwIjoxNzcwMTQ4NjU2fQ.UU04sbb10rcXB7s0XFJ7-Ci-y3dpxGh-EqDl7kuNgHA

### Create Cashier
POST http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiOWNkZTQ5LTdjYmMtNDFmOS04NGU3LTY5YWI2ZjdjMDBjNSIsImVtYWlsIjoid3VkaXJpMUBnbWFpbC5jb20iLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJ0ZW5hbnRJZCI6ImNlMGEyOWM3LWUzZDUtNGViMi1iYzIzLTg3NGFjNmM2YjMxNSIsImlhdCI6MTc2OTUwMjk4MiwiZXhwIjoxNzcwMTA3NzgyfQ.p6vlOjRyMGBR0kB-T4DWF7EzF7OjBR1ZFwuHZQJ-sIg
Content-Type: application/json

{
  "name": "Cashier One",
  "email": "cashier@demo.com",
  "password": "Password123",
  "role": "CASHIER"
}

### update user provide ID 
PUT http://localhost:5000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiOWNkZTQ5LTdjYmMtNDFmOS04NGU3LTY5YWI2ZjdjMDBjNSIsImVtYWlsIjoid3VkaXJpMUBnbWFpbC5jb20iLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJ0ZW5hbnRJZCI6ImNlMGEyOWM3LWUzZDUtNGViMi1iYzIzLTg3NGFjNmM2YjMxNSIsImlhdCI6MTc2OTUwMjk4MiwiZXhwIjoxNzcwMTA3NzgyfQ.p6vlOjRyMGBR0kB-T4DWF7EzF7OjBR1ZFwuHZQJ-sIg
Content-Type: application/json

{
  "name": "wudiri",
  "role": "TENANT_ADMIN"
}
